### ISSUE TITLE
installation fails?

### ISSUE THREAD

**Issue by barbalex** [kartoza/SpeciesExplorer#2]
Hey, thanks a lot for this great tool!

When trying to install it I get this error:
```
Erweiterungsinstallation schlug fehl: Error transferring https://plugins.qgis.org/plugins/SpeciesExplorer/version/0.1/download/ - server replied: Bad Gateway
```

It sounds as if the server in charge is having a problem. That may be something you have no influence over? Maybe I just have to wait a little...

More info:
- repository: https://plugins.qgis.org/plugins/plugins.xml
- QGIS-Version: 3.2.2

O.k., got it: https://plugins.qgis.org/plugins/plugins.xml responds with `bad gateway`. Closing

**Comment by timlinux** [comment]
Is it working now @barbalex ?

**Comment by timlinux** [comment]
If you do still have issues, you can take the plugin .zip from https://github.com/kartoza/SpeciesExplorer/releases/tag/0.1.0 and install it from zip using the QGIS plugin manager.

**Comment by barbalex** [comment]
thanks, everything is fine now - server was down a few hours
thanks also for the .zip file tip
